# themes from https://github.com/alacritty/alacritty-theme

import = ["~/.config/alacritty/themes/themes/catppuccin_macchiato.toml"]

[font]
size = 15

[font.normal]
family = "JetBrains Mono"

[window.padding]
x = 7
y = 0
