#!/bin/bash

# This is the setup script for my config. The idea is to be able to run
# this after cloning the repo on a Mac or Ubuntu (WSL) system and be up
# and running very quickly.

# create directories
export XDG_CONFIG_HOME="$HOME"/.config
mndir -p "$XDG_CONFIG_HOME"/bash
mkdir -p "$XDG_CONFIG_HOME"/alacritty
mkdir -p "$XDG_CONFIG_HOME"/alacritty/themes
mkdir -p "$XDG_CONFIG_HOME"/skhd
mkdir -p "$XDG_CONFIG_HOME"/tmux
# mkdir -p "$XDG_CONFIG_HOME"/wezterm

git clone https://github.com/alacritty/alacritty-theme "$XDG_CONFIG_HOME"/alacritty/themes

  Symbolic links

ln -sf "$PWD/alacritty.toml" "$XDG_CONFIG_HOME"/alacritty/alacritty.toml
ln -sf "$PWD/starship/starship.toml" "$XDG_CONFIG_HOME"/starship.toml
ln -sf "$PWD/.bash_profile" "$HOME"/.bash_profile
ln -sf "$PWD/.bashrc" "$HOME"/.bashrc
ln -sf "$PWD/.inputrc" "$HOME"/.inputrc
ln -sf "$PWD/tmux/.tmux.conf" "$XDG_CONFIG_HOME"/tmux
ln -sf "$PWD/nvim" "$XDG_CONFIG_HOME"/nvim
ln -sf "$PWD/skhdrc" "$XDG_CONFIG_HOME"/skhd/skhdrc
ln -sf "$PWD/newsboat/config" "$HOME"/.newsboat/config
ln -sf "$PWD/newsboat/urls" "$HOME"/.newsboat/urls

# Packages

# install brew
/bin/bash -c "$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/HEAD/install.sh)"

brew install --cask font-jetbrains-mono-nerd-font
brew install --cask alacritty
brew install tmux
brew install starship

# ubuntu packages apt
sudo apt install ripgrep gh

# ubuntu apt neovim setup
sudo apt install gcc g++ unzip

# ubuntu brew for neovim setup
# programming languages
brew install neovim go lazygit rust python node 

