#!/bin/bash

# This is the setup script for my config.

# create directories
export XDG_CONFIG_HOME="$HOME"/.config
mkdir -p "$XDG_CONFIG_HOME"/tmux
mkdir -p "$XDG_CONFIG_HOME"/ghostty

git clone https://github.com/tmux-plugins/tpm ~/.tmux/plugins/tpm
# Symbolic links

ln -sf "$PWD/.bash_profile" "$HOME"/.bash_profile
ln -sf "$PWD/.bashrc" "$HOME"/.bashrc
ln -sf "$PWD/.inputrc" "$HOME"/.inputrc
ln -sf "$PWD/tmux/.tmux.conf" "$XDG_CONFIG_HOME"/tmux
ln -sf "$PWD/newsboat/config" "$HOME"/.newsboat/config
ln -sf "$PWD/newsboat/urls" "$HOME"/.newsboat/urls
ln -sf "$PWD/ghostty/config" "$XDG_CONFIG_HOME"/ghostty
ln -sf "$PWD/starship/starship.toml" "$XDG_CONFIG_HOME"/starship.toml
ln -sf "$PWD/nvim" "$XDG_CONFIG_HOME"/nvim
ln -sf "$PWD/aerospace.toml" "$XDG_CONFIG_HOME"/aerospace/aerospace.toml

# Install Brew
/bin/bash -c "$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/HEAD/install.sh)"

# ------------ Misc ------------ #
brew install --cask font-jetbrains-mono-nerd-font
brew install --cask nikitabobko/tap/aerospace
brew install neovim

# ----------- Shell ---------- #
# Get up to date bash
brew install bash
brew install --cask ghostty
brew install jq
brew install tmux
brew install starship
brew install bat

# ---------- TUIs ---------- #
brew install lazygit
brew install lazydocker


# ---------- Programming Languages --------- #
brew install go rust python node 

# ---------- Global Config ---------- #
git config --global core.editor "nvim"

